In [2]:
import numpy as np

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from pytransform3d.rotations import *

## Operação de Rotação

${}^A\mathbf{P} = \mathbf{R}(\theta) {}^B\mathbf{P} = 
\begin{bmatrix}
\cos(\theta) & -\sin(\theta) & 0 & q_x\\
\sin(\theta) & \cos(\theta) & 0 & q_y\\
0 & 0 & 1 & q_z\\ 
0 & 0 & 0 & 1\\
\end{bmatrix}.
\begin{bmatrix}
{}^Bp_x\\
{}^Bp_y\\
{}^Bp_z\\
1
\end{bmatrix}$

In [3]:
theta = 30
angle = 'deg'

In [4]:
def rotation_matrix(theta, angle = 'rad'):
    if angle == 'deg':
        theta = np.deg2rad(theta)
    rotate_matrix = np.array([[np.cos(theta),   -np.sin(theta),  0.],
                            [np.sin(theta),     np.cos(theta),  0.],
                            [0.,                 0.,              1.]])
    return np.round(rotate_matrix,2)

In [5]:
P_b = np.array([[1.],[0.],[0.]])

In [5]:
# exemplo da matrix de rotacao em 20 graus
rotation_matrix(30, angle='deg')

array([[ 0.87, -0.5 ,  0.  ],
       [ 0.5 ,  0.87,  0.  ],
       [ 0.  ,  0.  ,  1.  ]])

In [6]:
print(P_b)

[[1.]
 [0.]
 [0.]]


In [6]:
P_a = np.dot(rotation_matrix(180, angle='deg'),P_b)

In [7]:
print(P_a)

[[-1.]
 [ 0.]
 [ 0.]]


In [9]:
matrix_from_euler_xyz([0, 0, 0.3])

array([[ 0.95533649,  0.29552021,  0.        ],
       [-0.29552021,  0.95533649,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [10]:
rotation_matrix(0.3, angle='rad')

array([[ 0.96, -0.3 ,  0.  ],
       [ 0.3 ,  0.96,  0.  ],
       [ 0.  ,  0.  ,  1.  ]])

${}^A\mathbf{P} = \mathcal{A}_0^1 {}^B\mathbf{P} = 
\begin{bmatrix}
\cos(\theta) & -\sin(\theta) & 0 & q_x\\
\sin(\theta) & \cos(\theta) & 0 & q_y\\
0 & 0 & 1 & q_z\\ 
0 & 0 & 0 & 1\\
\end{bmatrix}.
\begin{bmatrix}
{}^Bp_x\\
{}^Bp_y\\
{}^Bp_z\\
1
\end{bmatrix}$

In [8]:
def th(theta, Q):
    if angle == 'deg':
        theta = np.deg2rad(theta)
    th_matrix = np.array([[np.cos(theta),   -np.sin(theta), 0.,      Q[0]],
                          [np.sin(theta),   np.cos(theta),  0.,      Q[1]],
                          [0.,        0.,                   1.,      Q[2]],
                          [0.,        0.,                   0.,      1.]])
    return th_matrix

In [9]:
P_b = np.array([[1.],[0.],[0.]])
P_a = np.zeros((4,1))

In [10]:
P_b = np.vstack((P_b, [1]))

In [12]:
print(P_b)

[[1.]
 [0.]
 [0.]
 [1.]]


In [14]:
Q_a = np.array([3.,2.,1.])

In [15]:
P_a = np.dot(th(np.deg2rad(20),Q_a), P_b)

In [16]:
print(P_a)

[[3.99998144]
 [2.00609231]
 [1.        ]
 [1.        ]]


In [19]:
R=rotation_matrix(67, angle='rad')

In [20]:
np.dot(R,R.T)

array([[ 1.0100000e+00, -2.1938007e-17,  0.0000000e+00],
       [-2.1938007e-17,  1.0100000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])